### ISSUE TITLE
white links on pink background

### ISSUE THREAD

**Issue by bradreeder** [Jwhiles/john-whiles-dot-com#28]
Ask others for feedback on this, but I get a bit of glare from this particular contrast of shades.

**Comment by nelsonic** [comment]
@Jwhiles what @bradreeder said. 😉  👍 

# _expanding_ on it a bit ...

White links on a pink background ... 🤔 

![johnwhiles-cv-white-links-pink-background](https://cloud.githubusercontent.com/assets/194400/22013202/c7b3ac4c-dc8f-11e6-971d-661304c9e316.png)

## Background Reading 

+ https://www.viget.com/articles/color-contrast
+ http://graphicdesign.stackexchange.com/questions/15142/which-is-easier-on-the-eyes-dark-on-light-or-light-on-dark
+ http://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/
+ https://www.nngroup.com/articles/text-over-images

## Great Example Personal CV Website

if you're looking for a _personal_ site of a F&C 4 Grad that gets _results_, 
look no further than @markwilliamfirth  http://markwilliamfirth.com 😍  `#textbook`

![mark-1](https://cloud.githubusercontent.com/assets/194400/22013223/e16056cc-dc8f-11e6-98f8-6f1c13645f21.png)

![mark-2](https://cloud.githubusercontent.com/assets/194400/22013227/e48540f6-dc8f-11e6-97be-0239e5c85c65.png)

![mark-3](https://cloud.githubusercontent.com/assets/194400/22013228/e856fe86-dc8f-11e6-87f8-6f63d4fb01c1.png)

![mark-4](https://cloud.githubusercontent.com/assets/194400/22013229/ea70e22c-dc8f-11e6-9fa1-2e99de5a6a62.png)

Mark might not be working as a "developer", 
but he certainly is _leveraging technology to solve real human challenges_
and has a _high positive impact_ on the world. ❤️  ✅ 
If anything he hasn't allowed himself to be "_pigeon-holed_" as a "Dev".

# Learning from the _Best_

If you're searching for a GitHub-based CV that tells your prospective employer 
**_everything_ they need to know** in ***less than a minute*** - _which, let's face it, is an exceeding **generous** amount of time for someone who's time is worth £3/minute which is the case for "Engineering Managers" at top tech firms_ - have a look at: 
+ @Neats29 (F&C 4): https://github.com/Neats29/CV 
and/or 
+ @heron2014 (F&C 5): https://github.com/heron2014/CV

# tl;dr

Here's the "***user story***" you are solving for:

> As a `tech lead` who's **time is _scarce_**
> (_20+ team members & multiple projects demanding my attention and 100 CVs to read..._),
> I want to be **impressed** by a candidate
> in the ***first 5 seconds***
> so that I **_know_ the person**
> is **not _wasting_ my time**.

## No Personal Website...?

I'm _lucky_ in that I don't _have_ a personal website, 
it's not an "_accident_" or "_laziness_" ...
(_they are a lot of work to **maintain** and more often than not just show **narcissism**. 
not sayin' that's the case for your site, just in general..._) 

> I discovered pretty early on that **personal websites** _only **matter** if they are **amazing**_.

I _often_ think: would I be _more_ successful with a slick personal site. 
usually conclude: probably, yes.
But then I think about all my peers who have sites 
and how most of them aren't _making_ anything particularly interesting...
and end up going back to focussing on my work...

> _[**Content**](https://github.com/dwyl/the-book/issues/69) is the best_ [***calling card***](https://youtu.be/qwOdU02SE0w).

_However_...

## Expert Mode

`Given` that you already have a personal website and [_domain_](https://www.techopedia.com/definition/22799/vanity-domain)

If you ever decide to "shoot for the stars" and by leveling up to "**expert mode**": 
look at what @jongold is doing on http://jon.gold 😮 
he still has a http://www.jon.gold/txt for SEO/"findability"
(_sometimes I think he has too much time! 
but then I remember he's just 
doing what he [loves](https://twitter.com/jongold/status/817459894789865474)
so isn't "watching the clock" 
when he's in his [element](https://youtu.be/3TAqSBMZDY8) ..._)
BTW: someone who _consistently_ prioritises [_getting out_](https://twitter.com/jongold/status/779333838195556352) [_of the building_](https://github.com/foundersandcoders/master-reference/issues/64) 
though not at the "_expense_" of his [_deep_](https://github.com/dwyl/hq/issues/169) technical knowledge/skill ... 😉 
Highly recommend reading: 
+ http://www.jon.gold/2015/07/functional-css/
+ http://www.jon.gold/2016/04/a-single-craft/
+ http://www.jon.gold/2016/06/declarative-design-tools/

> A personal website with _regularly updated content_ is 😍 
there's a _reason_ why @jongold is at the _top_ of his game, 
***so grateful*** we got to ["hangout" with (_and be **inspired** by_) him](https://www.meetup.com/Meteor-London/events/173719312/)  `before` he was ["_famous_"](https://twitter.com/jongold/status/755214622022569984) 
and know he's just a (_really_) _nice_ guy who _happens_ to be [***insanely talented***](https://twitter.com/jongold/status/804968786793091072)
and [works really hard](https://youtu.be/GtaxU6DZvLs?t=8s) when nobody is _watching_... 
Jon is [Living the "Tech Nomad" Dream](https://twitter.com/jongold/status/795517581235015680) ❤️ 
By contrast, @cwaring doesn't _have_ a "personal CV website" 
but he no less talented/successful than Jon... 🤔 

(_and even then I've seen other member of a hiring panel reject people who had "sick" personal websites because they hadn't been updated in ages or simply didn't show the skills they were claiming on their CV... but I digress..._)

## Conclusino

_Most_ of the time the "_Recruiter_" or "_Hiring Manager_" is only searching for keywords.
So having a good LinkedIn profile (_with the keywords you want to be "**found**" for_)
which then links to a GitHub profile which shows _deliberate practice_ 
is _more than enough_ for them to pick up the phone and call you.

> Your site is looking **_good_ so far**.
 But as a middle-class-white-male, 
you might want to _do_/_make_ something to _stand out_.

It's ***less*** about the ***words*** on the page (_or the colors for that matter_) 
and ***more*** about _demonstrating_ ***craft***.

**Comment by Jwhiles** [comment]
Thanks for all the help nelson

These links should now be #0093FF :)

I'm going to close this, as I think discussion has moved to the above referenced issues.
